name: strict
version: 1.0.0
description: A heavily opinionated analysis_options for Dart/Flutter projects with strict - but justified - lint rules
repository: https://github.com/olmps/strict
issue_tracker: https://github.com/olmps/strict/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
